name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package binaries
        run: |
          chmod +x package.sh
          ./package.sh

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "$GITHUB_REF" >/dev/null 2>&1; then
            echo "Tag $GITHUB_REF already exists."
            exit 1
          fi

      - name: Create GitHub Release
        id: create_release
        if: steps.check_tag.outcome != 'failure'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset - macOS
        if: steps.check_tag.outcome != 'failure'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          asset_path: target/md-cms-macos
          asset_name: md-cms-macos
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset - Linux
        if: steps.check_tag.outcome != 'failure'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          asset_path: target/md-cms-linux
          asset_name: md-cms-linux
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset - Windows
        if: steps.check_tag.outcome != 'failure'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          asset_path: target/md-cms-win.exe
          asset_name: md-cms-win.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}